<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>Bin Card — {{ $header['product_code'] }}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 8.5pt; color: #1e293b; background: #fff; }

  /* ── Page layout ── */
  .page { padding: 20px 24px 14px; }

  /* ── Header ── */
  .header { width: 100%; margin-bottom: 10px; }
  .header table { width: 100%; }
  .company-name { font-size: 12pt; font-weight: 700; color: #111827; }
  .company-sub  { font-size: 7.5pt; color: #475569; margin-top: 1px; line-height: 1.4; }
  .doc-title    { font-size: 15pt; font-weight: 700; color: #111827; text-align: right; letter-spacing: 0.2px; white-space: nowrap; }
  .doc-sub      { font-size: 7.5pt; color: #475569; text-align: right; margin-top: 2px; }

  /* ── Info grid ── */
  .info-table { width: 100%; border-collapse: collapse; border-top: 1px solid #cbd5e1; border-bottom: 1px solid #cbd5e1; margin-bottom: 10px; }
  .info-table td { font-size: 7.8pt; padding: 3px 4px; vertical-align: top; }
  .info-label { color: #475569; white-space: nowrap; }
  .info-value { font-weight: 700; color: #111827; }

  /* ── Items table ── */
  .items-table { width: 100%; border-collapse: collapse; }
  .items-table th { background: #e2e8f0; color: #111827; font-size: 7.3pt; font-weight: 700; text-transform: uppercase; letter-spacing: 0.3px; padding: 5px 4px; border-bottom: 1px solid #cbd5e1; text-align: left; }
  .items-table td { font-size: 8pt; padding: 4px; border-bottom: 1px solid #f1f5f9; vertical-align: top; color: #1e293b; }
  .items-table tfoot td { border-top: 1px solid #cbd5e1; border-bottom: none; font-weight: 700; padding-top: 5px; }
  .mono  { font-family: 'DejaVu Sans Mono', monospace; font-size: 7.5pt; color: #475569; }
  .bold  { font-weight: 700; }
  .muted { color: #94a3b8; }
  .ta-r  { text-align: right; }
  .opening-row td { background: #f8fafc; font-weight: 700; font-style: italic; }

  /* ── Footer ── */
  .footer { border-top: 1px solid #e2e8f0; margin-top: 16px; padding-top: 8px; font-size: 6.8pt; color: #94a3b8; text-align: center; }
</style>
</head>
<body>
<div class="page">

  @php
    $fmt = fn ($n) => number_format((float) $n, 2);
  @endphp

  {{-- ══ HEADER ══════════════════════════════════════════════ --}}
  <div class="header">
    <table>
      <tr>
        <td style="width:55%; vertical-align:top;">
          @if($header['company_name'])
          <div class="company-name">{{ $header['company_name'] }}</div>
          @if($header['company_address'])
          <div class="company-sub">{{ $header['company_address'] }}</div>
          @endif
          @if($header['company_email'])
          <div class="company-sub">{{ $header['company_email'] }}</div>
          @endif
          @endif
        </td>
        <td style="width:45%; vertical-align:top;">
          <div class="doc-title">BIN CARD REPORT</div>
          <div class="doc-sub">
            Period: {{ $header['date_from'] ?? 'Beginning' }} — {{ $header['date_to'] ?? 'To Date' }}
          </div>
        </td>
      </tr>
    </table>
  </div>

  {{-- ══ INFO GRID ═══════════════════════════════════════════ --}}
  <table class="info-table">
    <tr>
      <td class="info-label">Product Code :</td>
      <td class="info-value">{{ $header['product_code'] }}</td>
      <td class="info-label">Location :</td>
      <td class="info-value">{{ $header['location_name'] ?? 'All' }}</td>
      <td class="info-label">Generated By :</td>
      <td class="info-value">{{ $header['generated_by'] }}</td>
    </tr>
    <tr>
      <td class="info-label">Product Name :</td>
      <td class="info-value">{{ $header['product_name'] }}</td>
      <td class="info-label">Store :</td>
      <td class="info-value">{{ $header['store_name'] ?? 'All' }}</td>
      <td class="info-label">Generated Time :</td>
      <td class="info-value">{{ $header['generated_at'] }}</td>
    </tr>
    <tr>
      <td class="info-label">Reorder Level :</td>
      <td class="info-value">{{ $fmt($header['reorder_level']) }}</td>
      <td class="info-label">Stock In Hand :</td>
      <td class="info-value">{{ $fmt($header['stock_in_hand']) }}</td>
      <td class="info-label">Reorder Qty / Period :</td>
      <td class="info-value">{{ $fmt($header['reorder_qty']) }} / {{ $header['reorder_period'] ?? '—' }}</td>
    </tr>
  </table>

  {{-- ══ LEDGER TABLE ════════════════════════════════════════ --}}
  <table class="items-table">
    <thead>
      <tr>
        <th style="width:24px;">#</th>
        <th style="width:70px;">Date</th>
        <th>Description</th>
        <th style="width:90px;">Document No</th>
        <th class="ta-r" style="width:70px;">Stock IN</th>
        <th class="ta-r" style="width:70px;">Stock Out</th>
        <th class="ta-r" style="width:80px;">Stock Balance</th>
      </tr>
    </thead>
    <tbody>
      @if($opening['show'])
      <tr class="opening-row">
        <td></td>
        <td>{{ $header['date_from'] }}</td>
        <td>Opening Balance</td>
        <td class="mono">—</td>
        <td class="ta-r">—</td>
        <td class="ta-r">—</td>
        <td class="ta-r">{{ $fmt($opening['balance']) }}</td>
      </tr>
      @endif

      @forelse($rows as $i => $row)
      <tr>
        <td class="muted">{{ $i + 1 }}</td>
        <td>{{ $row['date'] }}</td>
        <td>{{ $row['description'] }}</td>
        <td class="mono">{{ $row['document_no'] }}</td>
        <td class="ta-r">{{ $row['qty_in'] > 0 ? $fmt($row['qty_in']) : '—' }}</td>
        <td class="ta-r">{{ $row['qty_out'] > 0 ? $fmt($row['qty_out']) : '—' }}</td>
        <td class="ta-r bold">{{ $fmt($row['balance']) }}</td>
      </tr>
      @empty
      <tr>
        <td colspan="7" class="muted" style="text-align:center; padding:14px;">No stock transactions found for the selected filters.</td>
      </tr>
      @endforelse
    </tbody>
    <tfoot>
      <tr>
        <td colspan="4" class="ta-r">Total</td>
        <td class="ta-r">{{ $fmt($summary['total_in']) }}</td>
        <td class="ta-r">{{ $fmt($summary['total_out']) }}</td>
        <td class="ta-r">{{ $fmt($summary['closing_balance']) }}</td>
      </tr>
    </tfoot>
  </table>

  {{-- ══ FOOTER ══════════════════════════════════════════════ --}}
  <div class="footer">
    Generated by {{ $header['generated_by'] }} on {{ $header['generated_at'] }}
  </div>

</div>
</body>
</html>
